<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\StudioAgenda.Exceptions\StudioAgenda.Exceptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\Respostas\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
